### ISSUE TITLE
What are the main differences of 8kdata/phoebe and alaisi/postgres-async-driver?

### ISSUE THREAD

**Issue by vlsi** [8kdata/phoebe#8]
https://github.com/alaisi/postgres-async-driver, https://github.com/davidmoten/rxjava-jdbc

**Comment by valgog** [comment]
One of the biggest differences is that we know who writes Phoebe personally
😀

**Comment by ahachete** [comment]
On 18/12/15 11:33, Vladimir Sitnikov wrote:

> https://github.com/alaisi/postgres-async-driver, 
> https://github.com/davidmoten/rxjava-jdbc

```
 Hi Vladimir!

 Phoebe has been born with some clear goals in mind that were not 
```

found elsewhere. The mains ones are:
1. Create an independent layer to handle and abstract away PostgreSQL's 
   wire protocol (this is phoebe-common in Phoebe). This layer is meant to 
   provide a clean API to send/receive PostgreSQL wire protocol messages 
   without having to know details about them and their wire format. This 
   layer could serve as a basis for any PostgreSQL-protocol related tool, 
   such as drivers, connection poolers or even PostgreSQL-like servers.
2. Remain compatible with Java 6.
3. Provide a highly asynchronous, non-JDBC driver, with a Reactive approach.
4. Add tons of features (see below) not present in current attempts.
   
    IMHO, Postgres async driver does not address #1, #2 and more or 
   less #4. RxJava-JDBC does not address #1, #3 and again #4. Though both 
   of them look like really cool projects :)
   
    Regarding #1, I see a lot of code duplication among PostgreSQL 
   drivers. All of them have their own wire layer implementation, and most 
   of them are based on Netty. But this layer is not modular, not reusable. 
   I'd love to have such a layer, that would help JVM coders do anything 
   related with PostgreSQL networking with a clean API and abstraction 
   about the protocol. This also implies #2, as that's their only option if 
   phoebe-common would eventually become a base dependency for any Postgres 
   driver (including pgjdbc).
   
    Currently, phoebe-common (although far from complete) addresses 
   this, and is a layer potentially reusable by both PostgreSQL clients and 
   servers. The current design is meant to be really efficient in terms of 
   heap memory consumption (it tries to to zero-copy: messages are just 
   views on the Netty ByteBufs allocated on direct memory, constant headers 
   are cached) and easy to use.
   
    Then there is a (currently tiny) client layer that provides some 
   client primitives. This layer is meant to serve as a meta-driver, the 
   real dependency on which drivers may be built (phoebe-common could also 
   be such a layer, but it's lower-level). This layer adds protocol client 
   state-machine, client interfaces and some other helpers.
   
    And then there is the Phoebe driver itself, which is just a driver 
   built on top of the previous two layers. It wants to achieve many 
   features currently not present in other drivers, like:
- Replication protocol support (to provide an answer to applications 
  that want to do, for instance, logical decoding)
- Query pipelining
- Unix Domain Sockets support
- An API designed to target PostgreSQL clusters (like Master-Slaves 
  setups) rather than individual nodes, and be aware of this concept when 
  issuing queries
- Reactive, but based on the reactive standards (aka Reactive Streams, 
  rather than directly depending on RxJava)
- Built in support for logical decoding
  
   Phoebe is still in its infancy. But I'd say progress looks good. 
  I'd love to see more collaboration towards phoebe-common and have it in 
  the future be reused across other PostgreSQL Java projects, such as 
  drivers. There has been some public discussion on the features, API and 
  goals for this project in the very-low-traffic Phoebe mail group: 
  https://groups.google.com/forum/#!forum/phoebe If you want to know more, 
  read some of the previous threads, and feel free to ask any further 
  questions.
  
   Your help is wanted! :)
  
   Cheers,
  
   Álvaro

## 

Álvaro Hernández Tortosa

---

8Kdata

**Comment by ahachete** [comment]
Please refer to https://groups.google.com/forum/#!forum/phoebe for further discussion about this topic. Closing the issue, please re-open if you consider it appropriate. Thanks!
